name: Manual Multi-Platform Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version (e.g., v1.5.31) or leave empty for latest main'
        required: false
        default: ''

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: '*.AppImage'
            asset_name_pattern: 'linux'
          - os: macos-latest
            artifact_name: '*.dmg'
            asset_name_pattern: 'mac'
          - os: windows-latest
            artifact_name: '*.exe'
            asset_name_pattern: 'windows'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || 'main' }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux
      
      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
      
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name_pattern }}-build
          path: dist-electron/${{ matrix.artifact_name }}
          retention-days: 1

  release:
    name: Upload to Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Display structure of downloaded files
        run: ls -R ./artifacts
      
      - name: Prepare release files
        run: |
          mkdir -p ./release-files
          # Копируем установочные файлы для всех платформ
          find ./artifacts/linux-build -type f -name "*.AppImage" -exec cp {} ./release-files/ \; 2>/dev/null || true
          find ./artifacts/mac-build -type f -name "*.dmg" ! -name "*.blockmap" -exec cp {} ./release-files/ \; 2>/dev/null || true
          find ./artifacts/windows-build -type f -name "*Setup*.exe" ! -name "*.blockmap" -exec cp {} ./release-files/ \; 2>/dev/null || true
          # Удаляем служебные файлы
          rm -f ./release-files/*.blockmap ./release-files/*.yml 2>/dev/null || true
          echo "=== Files prepared for release ==="
          ls -lh ./release-files || echo "No files found"
      
      - name: Get latest tag
        id: get_tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout for tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: ./release-files/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

